<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * English language strings for block_mad2api.
 *
 * @package   block_mad2api
 * @copyright 2025
 * @license   https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['apiurl'] = 'API URL';
$string['descconfig'] = 'Description of the config section';
$string['descfoo'] = 'Config description';
$string['headerconfig'] = 'Config section header';
$string['labelfoo'] = 'Config label';
$string['mad2api:addinstance'] = 'Add LANSE block';
$string['mad2api:myaddinstance'] = 'Add LANSE block to my moodle';
$string['pluginname'] = 'Dashboard LANSE';
$string['error_modal_title'] = 'Error on enabling course';
$string['access_dashboard'] = 'Access dashboard';
$string['open_dashboard'] = 'Open LANSE platform';
$string['enable_dashboard'] = 'Enable course monitoring';
$string['disable_dashboard'] = 'Disable course monitoring';
$string['load_data'] = 'Load course data now';
$string['not_teacher'] = 'To access the Dashboard, you need to be a teacher of the course.';
$string['error_modal_body'] = "
  <p>
    Please ensure that the course you are trying to enable has start date and end date configured correctly. If the problem persists, please contact us at: <b>suporte.lanse@gmail.com</b>. Thank you!
  </p>
";
$string['error_alert_body'] = 'Please ensure that the course you are trying to enable has start date and end date configured correctly. If the problem persists, please contact us at: suporte.lanse@gmail.com. Thank you!';

$string['privacy:metadata:course_logs'] = 'Logs generated by the block to register API interactions per user/course.';
$string['privacy:metadata:course_logs:courseid'] = 'Course ID related to the log entry.';
$string['privacy:metadata:course_logs:userid'] = 'User ID that originated the event/export.';
$string['privacy:metadata:course_logs:action'] = 'Action performed by the integration (e.g., enable, disable, export).';
$string['privacy:metadata:course_logs:payload'] = 'Payload sent or received during the API call (may contain personal data).';
$string['privacy:metadata:course_logs:status'] = 'Processing status/response of the API call.';
$string['privacy:metadata:course_logs:createdat'] = 'Creation timestamp of the log entry.';

$string['privacy:metadata:external'] = 'This plugin sends data to an external service (LANSE / MAD API) to provide dashboards and analytics.';
$string['privacy:metadata:external:userid'] = 'The identifier of the user in Moodle.';
$string['privacy:metadata:external:courseid'] = 'The identifier of the course in Moodle.';
$string['privacy:metadata:external:fullname'] = 'Full name of the user.';
$string['privacy:metadata:external:email'] = 'Email address of the user.';
$string['privacy:metadata:external:enrolments'] = 'User enrolments used for calculating access and permissions on the external dashboard.';
$string['privacy:metadata:external:grades'] = 'Grade information used for analytics.';
$string['privacy:metadata:external:progress'] = 'Progress/Activities completion information.';
$string['privacy:metadata:external:lastaccess'] = 'Last access timestamps used for activity indicators.';

$string['privacy:export:path'] = 'MAD2 API block data';

// view.php
$string['api_contact_error'] = 'Falha ao contatar a API (erro Moodle).';
$string['api_contact_error_retry'] = 'Falha ao contatar a API. Tente novamente mais tarde.';
$string['api_response_invalid'] = 'Resposta da API inválida.';
$string['api_token_missing'] = 'Token não recebido da API.';
$string['page_title'] = 'LANSE - Dashboard';
$string['page_heading'] = 'Dashboard LANSE - Curso: {$a->coursefullname}';
$string['post_message_error'] = 'Erro ao enviar postMessage para LANSE:';

// settings.php
$string['adminroles'] = 'Perfil Coordenador na LANSE';
$string['adminroles_desc'] = 'Perfis que terão acesso ao Plugin como coordenador';
$string['apikey'] = 'Chave API KEY Plugin';
$string['apiurl'] = 'URL da API';
$string['appurl'] = 'URL da plataforma';
$string['organization'] = 'Nome da organização';
$string['roles'] = 'Perfil Professor/Tutor na LANSE';
$string['roles_desc'] = 'Perfis que terão acesso ao Plugin como professor/tutor';
$string['studentrole'] = 'Selecione o papel de estudante na LANSE';
$string['studentrole_desc'] = 'Perfil utilizado para identificar os estudantes no Plugin';

// classes/task/mad_logger.php
$string['send_logs_task_name'] = 'Envio de Logs LANSE';
$string['check_resend_data_task_name'] = 'Verificação de Reenvio de Dados LANSE';
